services:
  chroma:
    image: chromadb/chroma:1.5.9
    ports:
      - "8001:8000"
    environment:
      IS_PERSISTENT: "TRUE"
      PERSIST_DIRECTORY: /chroma/chroma
    volumes:
      - ./.data/chroma:/chroma/chroma
